### ISSUE TITLE
OAuth2 Mechanism Support

### ISSUE THREAD

**Issue by genvmoroz** [emersion/go-sasl#21] opened 2022-08-02 09:32 UTC
Hi there, have you planned to implement OAuth2 mechanism for this library?
I'm looking forward to use `github.com/emersion/go-imap/client` IMAP client to get access to outlook.com using oauth2, is it possible for now? If not, do you have a plan to integrate it? If yes, when do you expect to integrate it?

Thanks in advance!

**Comment by emersion** [comment] 2022-08-02 09:34
Duplicate of https://github.com/emersion/go-sasl/issues/20

outlook.com uses a non-standard mechanism. OAUTHBEARER is the standard, but Microsoft only supports XOAUTH2.

**Closed by emersion** 2022-08-02 09:34 UTC

**Comment by genvmoroz** [comment] 2022-08-02 09:37
@emersion thank you, so that means your client does not support the oauth2 mechanism for outlook.com? Or is there some way to hack the system?
